### ISSUE TITLE
Using WSL instead of cygwin?

### ISSUE THREAD

**Issue by IMFUZZ** [starlight/swan-base#2]
Didn't want to open an issue for this but is it possible to use Window 10's WSL (Bash on Ubuntu on Windows) instead of Cygwin?

**Comment by isaacwhanson** [comment]
Not with Swan, currently.  I have heard reports the performance is terrible, and one report that you can use multi-window X mode to get performance near native.  I plan to look into this, but it would have to spawn a new project.  Also, I am fond of the idea that Swan does not need admin privileges to install - while getting WSL installed does.  Something I will research further at least.

**Comment by SharkWipf** [comment]
I'll add my 2 cents to this as I tried replicating Swan on WSL before.  
It is not possible to run Swan itself in its current form on WSL, as WSL is basically a "native Linux environment" (running native Linux binaries without change), while Swan is Cygwin based (Linux applications compiled to work as windows applications).  
It is, however, possible to run XFCE4 on WSL. You have to manually run an X server on Windows, configure WSL to use it and then run the applications you want.  
If you want a floating panel like Swan, you only need to run "xfce4-panel" and configure it.  

However, as @isaacwhanson said, YMMV:  
- I had to apply the fixes listed [here](https://www.reddit.com/r/Windows10/comments/4rsmzp/bash_on_windows_getting_dbus_and_x_server_working/) to get it working at all.  
- I'm on reasonably low-end hardware and on my PC it took >5 seconds to load any applications, while on Swan it takes <1s. It was unworkable for me.
