### ISSUE TITLE
first launch of console went very wrong

### ISSUE THREAD

**Issue by meeech** [starlight/swan-base#3]
Hi. Any info on what the console is trying to run when first launched. 
it tried to mv a bunch of stuff from AppData, but i already had cygwin setup on my system, and it seemed to break a bunch of stuff, since my windows home is my cygwin home. So it seemed to try to mv folder into itself, and broke a bunch of my setup. any pointer to what is exec'ing when launching swan console appreciated.

**Comment by meeech** [comment]
in case this happens to anyone else - i've configured my cygwin install to use my windows home folder (this helps for scenarios like .ssh folder being shared between win gui and cli progs). however, it seems like for some reason, Swan tries to **mv** the cygwin home folder into C:\Users\myUser\AppData\Roaming\Swan, so it pretty much messed up my system.

Sorry if this is in the wrong project - let me know.

**Comment by isaacwhanson** [comment]
Have a look at `/etc/profile.d/00-skel.sh`.  Sorry about that, didn't expect a setup like that.

**Comment by isaacwhanson** [comment]
@meeech If you are comfortable providing a fix, I would appreciate it...

**Comment by isaacwhanson** [comment]
Actually, I just removed the migration - leaving it up to the user.
