### ISSUE TITLE
Swan installer does not install bash?

### ISSUE THREAD

**Issue by jmjw** [starlight/swan-base#5]
When using the Swan Installer for doing a new installation of Swan, apparently no bash is installed in the installation directory. Is this correct?
I have an already installed version of cygwin in another directory.

**Comment by isaacwhanson** [comment]
It should install bash at `C:\ProgramData\Swan\bin\bash.exe` by default.

Note that running multiple cygwin processes from different installations at the same time will confuse cygwin.  There should be no problem if all the processes from one installation are terminated before starting processes from the other installation.

You may also install Swan into an existing cygwin installation using the Swan Installer to avoid that issue, but you won't be able to restore your original vanilla cygwin easily.
