### ISSUE TITLE
home and end hotkeys inserting tildes

### ISSUE THREAD

**Issue by sigmap** [starlight/swan-base#6]
I noticed this problem in babun as well and I don't know how to disable it. I like being able to press END and going to the end of a line and similar with the home key.

**Comment by SharkWipf** [comment]
Not sure what would cause this, it's working fine on my end, although I have seen the issue before in certain applications.  
But in xfce4-terminal/bash in Swan on Win10 home it's working fine for me.
Could it be a locale/language setting?

**Comment by sigmap** [comment]
On windows7 and this happens in mintty, the console as opposed to fully launching the xfce desktop.

**Comment by sigmap** [comment]
I should note it doesn't happen in plain cygwin.

**Comment by SharkWipf** [comment]
No problems in MinTTY here either, do you have it even in the plain bash shell? Or only in specific applications?

**Comment by sigmap** [comment]
plain bash
no changes to the install

**Comment by sigmap** [comment]
After some testing I found it related to terminfo. In babun it was only when I launched tmux and the default shell was zsh. It didn't seem to happen on anything that used readline. So I put something into my zshrc and it fixed. 
_I forgot I installed zsh_
The key mixup doesn't happen in bash
```zsh
    bindkey -- "\E[H"      beginning-of-line
    bindkey -- "\E[F"      end-of-line
    bindkey -- "\E[3~"      delete-char

 if [[ -n "$TMUX" ]]; then
    bindkey -- "\E[1~"      beginning-of-line
    bindkey -- "\E[4~"      end-of-line
 fi
```
